### ISSUE TITLE
Route53 fails to set required attributes to run correctly

### ISSUE THREAD

**Issue by hobosteaux** [komuw/sewer#168]
## Which version of python are you using?
3.6

## What operating system and version of operating system are you using?
Ubuntu 18.04

## What version of sewer are you using?
`f3eee5881372b3d76a6f719a558abc3e85737afc`

## What did you do? (be as detailed as you can)
Attempted to create a certificate.

## What did you expect to see/happen/not happen?
No errors from sewer

## What did you actually see/happen? 
Errors from sewer

## If you can, run sewer with loglevel set to debug; eg `sewer --loglevel DEBUG`                                           
```
Error: Unable to issue certificate. error='Route53Dns' object has no attribute 'auth_type'
Traceback (most recent call last):
  File "./certmanager.py", line 84, in <module>
    do_certs(config)
  File "./certmanager.py", line 72, in do_certs
    client.renew() + "\n" + client.certificate_key
  File "/home/eball/.local/share/virtualenvs/.../lib/python3.6/site-packages/sewer/client.py", line 776, in renew
    return self.cert()
  File "~/.local/share/virtualenvs/.../lib/python3.6/site-packages/sewer/client.py", line 767, in cert
    return self.get_certificate()
  File "~/.local/share/virtualenvs/.../lib/python3.6/site-packages/sewer/client.py", line 756, in get_certificate
    raise e
  File "~/.local/share/virtualenvs/.../lib/python3.6/site-packages/sewer/client.py", line 720, in get_certificate
    identifier_auth = self.get_identifier_authorization(url)
  File "~/.local/share/virtualenvs/.../lib/python3.6/site-packages/sewer/client.py", line 462, in get_identifier_authorization
    if i["type"] == self.auth_provider.auth_type:
AttributeError: 'Route53Dns' object has no attribute 'auth_type'
```

It looks like [this line](https://github.com/komuw/sewer/blob/master/sewer/dns_providers/route53.py#L43) is missing a `self`; it should be `super(Route53Dns, self).__init__()`.

**Comment by mmaney** [comment]
@hobosteaux Yes, that would probably do it.  Have you tested the fix?

Thanks

**Comment by hobosteaux** [comment]
Confirmed that the above change fixes the bug.
