### ISSUE TITLE
sewer non-binary install cannot be attempted on macos

### ISSUE THREAD

**Issue by stevenolen** [komuw/sewer#211]
## Which version of python are you using?

3.8.2

## What operating system and version of operating system are you using?

macos 10.15.5

## What version of sewer are you using?

0.8.3

## What did you do? (be as detailed as you can)

  * Included `sewer==0.8.3` in my project's `requirements.txt`
  * Ran `pip install -r requirements.txt --no-binary :all:` (attempted to install sewer without using binary)

## What did you expect to see/happen/not happen?

I expected the package to be installed.

## What did you actually see/happen?

The package failed to install

## Paste here the log output generated by `sewer`, if any. Please remember to remove any sensitive items from the log before pasting here.

```
Collecting sewer==0.8.3
  Using cached sewer-0.8.3.tar.gz (35 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/steve/.pyenv/versions/3.8.2/envs/fleeting/bin/python3.8 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/6j/0zzb6gq52l1bpn_d5dxbsfqc0000gn/T/pip-install-ox8v79_x/sewer/setup.py'"'"'; __file__='"'"'/private/var/folders/6j/0zzb6gq52l1bpn_d5dxbsfqc0000gn/T/pip-install-ox8v79_x/sewer/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/6j/0zzb6gq52l1bpn_d5dxbsfqc0000gn/T/pip-pip-egg-info-0qfwp57k
         cwd: /private/var/folders/6j/0zzb6gq52l1bpn_d5dxbsfqc0000gn/T/pip-install-ox8v79_x/sewer/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/6j/0zzb6gq52l1bpn_d5dxbsfqc0000gn/T/pip-install-ox8v79_x/sewer/setup.py", line 5, in <module>
        with codecs.open(os.path.join("docs", "README.md"), "r", encoding="utf8") as f:
      File "/Users/steve/.pyenv/versions/3.8.2/lib/python3.8/codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: 'docs/README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

## If you can, run sewer with loglevel set to debug; eg `sewer --loglevel DEBUG`                                           

N/A

**Comment by stevenolen** [comment]
@mmaney thank you kindly!
