### ISSUE TITLE
Error sending csr

### ISSUE THREAD

**Issue by maedox** [komuw/sewer#83]
## Which version of python are you using?
3.6.3

## What operating system and version of operating system are you uing?
Ubuntu 17.10

## What version of sewer are you using?
0.5.0

## What did you do? (be as detailed as you can)
```
virtualenv -p python3.6 sewer
cd sewer
bin/pip install apache-libcloud==2.1.0  # (because otherwise: https://issues.apache.org/jira/browse/LIBCLOUD-946)
bin/pip install sewer
export CLOUDFLARE_EMAIL=****
export CLOUDFLARE_API_KEY=****
bin/sewer --dns cloudflare --domain mdx.no --alt_domains '*.mdx.no' --email ****@gmail.com --action run --endpoint staging --loglevel DEBUG
```
## What did you expect to see/happen/not happen?
Valid certificate

## What did you actually see/happen? 
Exception

## Paste here the log output generated by `sewer`, if any. Please remember to remove any sensitive items from the log before pasting here.                                           
```

chosen_dns_provider. Using cloudflare as dns provider.
chosen_dns_provider. Using cloudflare as dns provider.
intialise_success, sewer_version=0.5.0, domain_names=['mdx.no', '*.mdx.no'], acme_server=https://acme-staging...
intialise_success, sewer_version=0.5.0, domain_names=['mdx.no', '*.mdx.no'], acme_server=https://acme-staging...
intialise_success, sewer_version=0.5.0, domain_names=['mdx.no', '*.mdx.no'], acme_server=https://acme-staging...
account key succesfully written to current directory.
account key succesfully written to current directory.
account key succesfully written to current directory.
acme_register
acme_register
acme_register
acme_register_success
acme_register_success
acme_register_success
apply_for_cert_issuance
apply_for_cert_issuance
apply_for_cert_issuance
apply_for_cert_issuance_success
apply_for_cert_issuance_success
apply_for_cert_issuance_success
get_challenge
get_challenge
get_challenge
get_challenge_success
get_challenge_success
get_challenge_success
create_dns_record
create_dns_record
create_dns_record
delete_dns_record
delete_dns_record
delete_dns_record
delete_dns_record_success
delete_dns_record_success
delete_dns_record_success
create_dns_record_end
create_dns_record_end
create_dns_record_end
check_authorization_status
check_authorization_status
check_authorization_status
check_authorization_status_success
check_authorization_status_success
check_authorization_status_success
respond_to_challenge
respond_to_challenge
respond_to_challenge
respond_to_challenge_success
respond_to_challenge_success
respond_to_challenge_success
get_challenge
get_challenge
get_challenge
get_challenge_success
get_challenge_success
get_challenge_success
create_dns_record
create_dns_record
create_dns_record
delete_dns_record
delete_dns_record
delete_dns_record
delete_dns_record_success
delete_dns_record_success
delete_dns_record_success
create_dns_record_end
create_dns_record_end
create_dns_record_end
check_authorization_status
check_authorization_status
check_authorization_status
check_authorization_status_success
check_authorization_status_success
check_authorization_status_success
respond_to_challenge
respond_to_challenge
respond_to_challenge
respond_to_challenge_success
respond_to_challenge_success
respond_to_challenge_success
send_csr
send_csr
send_csr
Error: Unable to issue certificate. error=Error sending csr: status_code=400 response={'type': 'urn:ietf:params:acme:error:malformed', 'detail': 'Order\'s status ("invalid") was not pending', 'status': 400}
Error: Unable to issue certificate. error=Error sending csr: status_code=400 response={'type': 'urn:ietf:params:acme:error:malformed', 'detail': 'Order\'s status ("invalid") was not pending', 'status': 400}
Error: Unable to issue certificate. error=Error sending csr: status_code=400 response={'type': 'urn:ietf:params:acme:error:malformed', 'detail': 'Order\'s status ("invalid") was not pending', 'status': 400}
delete_dns_record
delete_dns_record
delete_dns_record
delete_dns_record_success
delete_dns_record_success
delete_dns_record_success
delete_dns_record
delete_dns_record
delete_dns_record
delete_dns_record_success
delete_dns_record_success
delete_dns_record_success
Traceback (most recent call last):
  File "bin/sewer", line 11, in <module>
    sys.exit(main())
  File "/home/paal/.venvs/sewer/lib/python3.6/site-packages/sewer/cli.py", line 204, in main
    certificate = client.cert()
  File "/home/paal/.venvs/sewer/lib/python3.6/site-packages/sewer/client.py", line 665, in cert
    return self.get_certificate()
  File "/home/paal/.venvs/sewer/lib/python3.6/site-packages/sewer/client.py", line 654, in get_certificate
    raise e
  File "/home/paal/.venvs/sewer/lib/python3.6/site-packages/sewer/client.py", line 649, in get_certificate
    certificate_url = self.send_csr(finalize_url)
  File "/home/paal/.venvs/sewer/lib/python3.6/site-packages/sewer/client.py", line 489, in send_csr
    response=self.log_response(send_csr_response)))
ValueError: Error sending csr: status_code=400 response={'type': 'urn:ietf:params:acme:error:malformed', 'detail': 'Order\'s status ("invalid") was not pending', 'status': 400}
```

**Comment by maedox** [comment]
Also, what's up with the logging?

**Comment by komuw** [comment]
hi @maedox I'm looking into this. 

`Also, what's up with the logging?` : you don't like it's verbosity?

**Comment by maedox** [comment]
No no, verbosity is good. It's just confusing that it is repeating the same
messages two or three times. But that's another issue.

**Comment by komuw** [comment]
`repeating the same messages two or three times. ` 
yeah, I forgot and added multiple log handlers. I'll fix that as I fix the bigger issue.

by the way, thanks for filing an issue

**Comment by komuw** [comment]
A subset of bugs identified in this issue have been resolved by this pull request: https://github.com/komuw/sewer/pull/87 
Namely:
- duplicate logging
-  inability to get certificates due to our handling of order of identifiers and authorizations array
in cert issuance request

However one issue  still remains; 
ie if you request for a certificate for  `example.com` and `*.example.com` then you'll get a failure. 
This issue is been worked on in PR; https://github.com/komuw/sewer/pull/84

However requesting for certificates for other domain name combinations now works okay. 
eg requesting certificates for `example.com` and `blog.example.com` is now fixed

**Comment by komuw** [comment]
@maedox Hi, this issue is now fixed in the latest version of sewer(https://pypi.python.org/pypi/sewer) 
via PR: https://github.com/komuw/sewer/pull/84
